service: notification-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  profile: serverless
  region: eu-west-3
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  apiGateway:
    shouldStartNameWithService: true
  iamRoleStatements:
    - ${file(iam/SendMailIAM.yml):SendMailIAM}
    - ${file(iam/MailQueueIAM.yml):MailQueueIAM}

  environment:
    SES_REGION: ${self:provider.region}
    SES_SOURCE: ${self:custom.sesSourceEmail}

resources:
  Resources:
    MailQueue: ${file(resources/MailQueue.yml):MailQueue}

functions:
  sendMail:
    handler: src/handlers/sendMail.handler
    events:
      - sqs:
          arn: ${self:custom.mailQueue.arn}
          batchSize: 1
          maximumRetryAttempts: 2

custom:
  mailQueue:
    name: MailQueue-${self:provider.stage}
    arn: !GetAtt MailQueue.Arn
  sesSourceEmail: andrew.akg.corp@gmail.com
